name: Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v2
        with:
          cache: true
          install: false
      - uses: oven-sh/setup-bun@v2
      - run: pnpm install --frozen-lockfile
      - run: bun run check:lint
      - run: bun run check:type
      - run: bun run test
      - run: bun run build
